### Starting TaskPrologue of job 2084596 on a0321 at Fri Oct  4 23:30:55 CEST 2024
Running on cores 0-31,48-63,96-111 with governor ondemand
Fri Oct  4 23:30:55 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.28.03              Driver Version: 560.28.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:01:00.0 Off |                  Off |
|  0%   33C    P8             22W /  300W |       1MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A40                     On  |   00000000:25:00.0 Off |                  Off |
|  0%   34C    P8             30W /  300W |       1MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A40                     On  |   00000000:61:00.0 Off |                  Off |
|  0%   34C    P8             21W /  300W |       1MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A40                     On  |   00000000:C1:00.0 Off |                  Off |
|  0%   34C    P8             21W /  300W |       1MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
### Finished TaskPrologue

start to run
True
CUDA_HOME is set to /home/hpc/v100dd/v100dd18/cuda-12.6
PATH is set to /home/hpc/v100dd/v100dd18/cuda-12.6/bin:/home/hpc/v100dd/v100dd18/cuda-12.6/bin:/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/bin:/home/hpc/v100dd/v100dd18/miniconda3/bin:/home/hpc/v100dd/v100dd18/miniconda3/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/apps/hpc-workspace/1.4.0/bin:/apps/hpc-workspace/1.4.0/bin
[2024-10-04 23:31:11,775] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W1004 23:31:15.446000 23070550516736 torch/distributed/run.py:779] 
W1004 23:31:15.446000 23070550516736 torch/distributed/run.py:779] *****************************************
W1004 23:31:15.446000 23070550516736 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1004 23:31:15.446000 23070550516736 torch/distributed/run.py:779] *****************************************
[2024-10-04 23:31:20,928] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/hpc/v100dd/v100dd18/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
[2024-10-04 23:31:24,944] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/hpc/v100dd/v100dd18/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
1. read arguments
[2024-10-04 23:31:25,453] [INFO] [comm.py:652:init_distributed] cdb=None
2. read model & tokenizer
[2024-10-04 23:31:25,984] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
1. read arguments
[2024-10-04 23:31:27,399] [INFO] [comm.py:652:init_distributed] cdb=None
2. read model & tokenizer
[2024-10-04 23:31:27,819] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:33,832] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-10-04 23:31:33,848] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/hpc/v100dd/v100dd18/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
Warning: The cache directory for DeepSpeed Triton autotune, /home/hpc/v100dd/v100dd18/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
1. read arguments
1. read arguments
[2024-10-04 23:31:35,996] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-10-04 23:31:35,996] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-10-04 23:31:35,996] [INFO] [comm.py:652:init_distributed] cdb=None
2. read model & tokenizer
2. read model & tokenizer
[2024-10-04 23:31:36,352] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:36,451] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:37,171] [INFO] [partition_parameters.py:348:__exit__] finished initializing model - num_params = 291, num_elems = 7.24B
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.37it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.37it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.34it/s]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:02<00:01,  1.41s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:02<00:01,  1.42s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:02<00:01,  1.42s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:06<00:12,  6.37s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  3.14s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.61s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  3.15s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.61s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  3.15s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.61s/it]
[2024-10-04 23:31:45,268] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:45,268] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:45,282] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:11<00:05,  5.88s/it]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:17<00:00,  5.83s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:17<00:00,  5.89s/it]
[2024-10-04 23:31:55,105] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 4
[2024-10-04 23:31:55,245] [INFO] [partition_parameters.py:348:__exit__] finished initializing model - num_params = 582, num_elems = 14.48B
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:05<00:10,  5.28s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:05<00:10,  5.30s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:05<00:10,  5.30s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:02,  2.81s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:02,  2.81s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:02,  2.82s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:02<00:04,  2.17s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.10s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.54s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.10s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.54s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.11s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:07<00:00,  2.54s/it]
3. read dataset
3. read dataset
3. read dataset
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:03<00:01,  1.75s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:04<00:00,  1.54s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:04<00:00,  1.64s/it]
3. read dataset
4. training
2024-10-04
4. training
2024-10-04
4. training
2024-10-04
4. training
2024-10-04
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
    wandb.init(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
    wandb.init(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
    wandb.init(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
    wi.setup(kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
    wandb_login._login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
    wi.setup(kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
    wi.setup(kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
    wandb_login._login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
    wandb_login._login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
    wandb.init(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
    wi.setup(kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
    wandb_login._login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
[rank1]:     wandb.init(
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
[rank1]:     wandb._sentry.reraise(e)
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
[rank1]:     raise exc.with_traceback(sys.exc_info()[2])
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
[rank1]:     wi.setup(kwargs)
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
[rank1]:     wandb_login._login(
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
[rank1]:     wlogin.prompt_api_key()
[rank1]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
[rank1]:     raise UsageError("api_key not configured (no-tty). call " + directive)
[rank1]: wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
[rank0]:     wandb.init(
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
[rank0]:     wandb._sentry.reraise(e)
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
[rank0]:     raise exc.with_traceback(sys.exc_info()[2])
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
[rank0]:     wi.setup(kwargs)
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
[rank0]:     wandb_login._login(
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
[rank0]:     wlogin.prompt_api_key()
[rank0]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
[rank0]:     raise UsageError("api_key not configured (no-tty). call " + directive)
[rank0]: wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
[rank2]:     wandb.init(
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
[rank2]:     wandb._sentry.reraise(e)
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
[rank2]:     raise exc.with_traceback(sys.exc_info()[2])
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
[rank2]:     wi.setup(kwargs)
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
[rank2]:     wandb_login._login(
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
[rank2]:     wlogin.prompt_api_key()
[rank2]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
[rank2]:     raise UsageError("api_key not configured (no-tty). call " + directive)
[rank2]: wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/hpc/v100dd/v100dd18/dpo/trl/./dpo_Tong.py", line 333, in <module>
[rank3]:     wandb.init(
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
[rank3]:     wandb._sentry.reraise(e)
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
[rank3]:     raise exc.with_traceback(sys.exc_info()[2])
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
[rank3]:     wi.setup(kwargs)
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
[rank3]:     wandb_login._login(
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
[rank3]:     wlogin.prompt_api_key()
[rank3]:   File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
[rank3]:     raise UsageError("api_key not configured (no-tty). call " + directive)
[rank3]: wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
W1004 23:38:48.452000 23070550516736 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3966849 closing signal SIGTERM
W1004 23:38:48.452000 23070550516736 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3966850 closing signal SIGTERM
W1004 23:38:48.452000 23070550516736 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 3966852 closing signal SIGTERM
E1004 23:38:48.666000 23070550516736 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 2 (pid: 3966851) of binary: /home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/bin/python
Warning: The cache directory for DeepSpeed Triton autotune, /home/hpc/v100dd/v100dd18/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    deepspeed_launcher(args)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 852, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./dpo_Tong.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-04_23:38:48
  host      : a0321.nhr.fau.de
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3966851)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
=== JOB_STATISTICS ===
=== current date     : Fri Oct  4 23:38:49 CEST 2024
= Job-ID             : 2084596 on alex
= Job-Name           : zephyr-7b_dpo_4
= Job-Command        : /home/hpc/v100dd/v100dd18/dpo/trl/run/run_dpo.sh
= Initial workdir    : /home/hpc/v100dd/v100dd18/dpo/trl/run
= Queue/Partition    : a40
= Slurm account      : v100dd with QOS=normal
= Requested resources:  for 1-00:00:00
= Elapsed runtime    : 00:07:57
= Total RAM usage    : 2.9 GiB of assigned  GiB (%)
= Node list          : a0321
= Subm/Elig/Start/End: 2024-10-04T23:30:52 / 2024-10-04T23:30:52 / 2024-10-04T23:30:52 / 2024-10-04T23:38:49
======================
=== Quota infos ======
    Path              Used     SoftQ    HardQ    Gracetime  Filec    FileQ    FiHaQ    FileGrace    
!!! /home/hpc          112.2G   104.9G   209.7G  -29703days     170K     500K   1,000K        N/A !!!
    /home/vault          0.0K  1048.6G  2097.2G        N/A       1      200K     400K        N/A    
======================
=== GPU utilization ==
gpu_name, gpu_bus_id, pid, gpu_utilization [%], mem_utilization [%], max_memory_usage [MiB], time [ms]
NVIDIA A40, 00000000:01:00.0, 3966849, 1 %, 0 %, 7944 MiB, 434950 ms
NVIDIA A40, 00000000:25:00.0, 3966850, 5 %, 0 %, 15982 MiB, 443799 ms
NVIDIA A40, 00000000:61:00.0, 3966851, 5 %, 0 %, 15982 MiB, 434671 ms
NVIDIA A40, 00000000:C1:00.0, 3966852, 5 %, 0 %, 15962 MiB, 447639 ms
