2024-10-05 20:27:58 ERROR Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 258, in login
    wandb.login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 85, in login
    configured = _login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

2024-10-05 20:33:27 ERROR Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 258, in login
    wandb.login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 85, in login
    configured = _login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

2024-10-05 20:36:05 ERROR Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/cli/cli.py", line 258, in login
    wandb.login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 85, in login
    configured = _login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 317, in _login
    wlogin.setup(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 141, in setup
    login_settings._apply_login(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1972, in _apply_login
    self.update(
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1528, in update
    self.__dict__[key].update(settings.pop(key), source=source)
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 600, in update
    self._value = self._validate(self._preprocess(value))
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 570, in _validate
    if not v(value):
  File "/home/hpc/v100dd/v100dd18/miniconda3/envs/simpo/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1068, in _validate_api_key
    raise UsageError("API key cannot start or end with whitespace")
wandb.errors.errors.UsageError: API key cannot start or end with whitespace

